/**
 * Blitz Puzzle set: deterministic bot self-play, scanning every position for
 * a forced mate. Mate-in-1 puzzles have exactly one mating move; mate-in-2
 * puzzles have exactly one checking key that forces mate (and no mate-in-1).
 * Writes packages/shared/src/puzzles.ts with positions only, never solutions.
 *
 *   pnpm --filter @risky-chess/engine gen:puzzles [games=4000]
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Chess } from 'chess.js';
import { START_FEN, type Puzzle } from '@risky-chess/shared';
import { positionKey, rankBotMoves, seededRng } from '../src';
import { mateIn2Keys, matingMoves } from '../src/originals/puzzles';

const here = dirname(fileURLToPath(import.meta.url));
const OUT = join(here, '../../shared/src/puzzles.ts');
const TARGET = { mate1: 150, mate2: 100 } as const;
const MAX_PLIES = 200;
const games = Number(process.argv[2] ?? 4000);

const seen = new Set<string>();
const puzzles: Puzzle[] = [];
const count = (tier: Puzzle['tier']) => puzzles.filter((p) => p.tier === tier).length;

function consider(fen: string): void {
  const key = positionKey(fen);
  if (seen.has(key)) return;
  seen.add(key);
  const chess = new Chess(fen);
  if (chess.isGameOver() || chess.inCheck()) return; // puzzles start quietly
  const mates = matingMoves(fen);
  if (mates.length === 1) {
    if (count('mate1') < TARGET.mate1) puzzles.push({ fen, tier: 'mate1' });
    return;
  }
  if (mates.length > 0 || count('mate2') >= TARGET.mate2) return;
  if (mateIn2Keys(fen, true).length === 1) puzzles.push({ fen, tier: 'mate2' });
}

const rng = seededRng(2026);
const started = Date.now();
for (let g = 0; g < games && (count('mate1') < TARGET.mate1 || count('mate2') < TARGET.mate2); g++) {
  const chess = new Chess(START_FEN);
  for (let ply = 0; ply < MAX_PLIES && !chess.isGameOver(); ply++) {
    // Skip the opening: mates there are rare and the positions all look alike.
    if (ply >= 16) consider(chess.fen());
    const ranked = rankBotMoves(chess.fen(), rng, 'greedy');
    // A little variety: the top three, weighted toward the best.
    const pick = ranked[Math.min(ranked.length - 1, [0, 0, 0, 1, 1, 2][rng.int(6)]!)]!.move;
    chess.move({ from: pick.from, to: pick.to, ...(pick.promotion ? { promotion: pick.promotion } : {}) });
  }
  if (g % 200 === 0) console.log(`game ${g}: mate1 ${count('mate1')} mate2 ${count('mate2')} (${Math.round((Date.now() - started) / 1000)}s)`);
}

const body = puzzles.map((p) => `  { fen: ${JSON.stringify(p.fen)}, tier: '${p.tier}' },`).join('\n');
writeFileSync(
  OUT,
  `// Generated by \`pnpm --filter @risky-chess/engine gen:puzzles\`: do not edit by hand.
// Positions only; the server verifies answers by search, so no solution ships to clients.
import type { Puzzle } from './types/originals';

export const PUZZLES: readonly Puzzle[] = [
${body}
];
`,
);
console.log(`wrote ${puzzles.length} puzzles (mate1 ${count('mate1')}, mate2 ${count('mate2')}) to ${OUT}`);
