// GENERATED by packages/engine/scripts/price-bets.ts — do not edit by hand.
// 2000 bot-vs-bot games per profile (each bet sampled for both colors, placed at turn 1),
// payoutX100 = clamp(floor(100 × (1 − 0.08) / p), 120, 1000). Generated at 40f5f06.
import type { PropBetKind } from './types/modes';

export interface BetPrice {
  /** Simulated probability the bet wins, among bets that settle won or lost. */
  p: number;
  /** floor(100 × (1 − 0.08) / p), clamped to 120–1000. */
  payoutX100: number;
  /** Settled (won or lost) samples behind `p`. */
  n: number;
}

/** Profile key (the active non-bet modes, e.g. "loaded_dice+all_in", or "base") → price per available kind. */
export const BET_ODDS: Record<string, Partial<Record<PropBetKind, BetPrice>>> = {
  'base': {
    opp_castles_by: { p: 0.0853, payoutX100: 1000, n: 4000 }, // won 341, lost 3659, void 0
    opp_promotes: { p: 0.1200, payoutX100: 766, n: 4000 }, // won 480, lost 3520, void 0
    game_length_under: { p: 0.2645, payoutX100: 347, n: 4000 }, // won 1058, lost 2942, void 0
    game_length_over: { p: 0.5685, payoutX100: 161, n: 4000 }, // won 2274, lost 1726, void 0
  },
  'loaded_dice': {
    opp_castles_by: { p: 0.0767, payoutX100: 1000, n: 4000 }, // won 307, lost 3693, void 0
    opp_promotes: { p: 0.1237, payoutX100: 743, n: 4000 }, // won 495, lost 3505, void 0
    opp_toss_upset: { p: 0.0219, payoutX100: 1000, n: 3978 }, // won 87, lost 3891, void 22
    game_length_under: { p: 0.2825, payoutX100: 325, n: 4000 }, // won 1130, lost 2870, void 0
    game_length_over: { p: 0.5330, payoutX100: 172, n: 4000 }, // won 2132, lost 1868, void 0
  },
  'odds_market': {
    opp_castles_by: { p: 0.0747, payoutX100: 1000, n: 4000 }, // won 299, lost 3701, void 0
    opp_promotes: { p: 0.1527, payoutX100: 602, n: 4000 }, // won 611, lost 3389, void 0
    opp_toss_upset: { p: 0.0404, payoutX100: 1000, n: 3984 }, // won 161, lost 3823, void 16
    game_length_under: { p: 0.1990, payoutX100: 462, n: 4000 }, // won 796, lost 3204, void 0
    game_length_over: { p: 0.6230, payoutX100: 147, n: 4000 }, // won 2492, lost 1508, void 0
  },
  'loaded_dice+odds_market': {
    opp_castles_by: { p: 0.0820, payoutX100: 1000, n: 4000 }, // won 328, lost 3672, void 0
    opp_promotes: { p: 0.1613, payoutX100: 570, n: 4000 }, // won 645, lost 3355, void 0
    opp_toss_upset: { p: 0.0397, payoutX100: 1000, n: 3978 }, // won 158, lost 3820, void 22
    game_length_under: { p: 0.2185, payoutX100: 421, n: 4000 }, // won 874, lost 3126, void 0
    game_length_over: { p: 0.5975, payoutX100: 153, n: 4000 }, // won 2390, lost 1610, void 0
  },
  'all_in': {
    opp_castles_by: { p: 0.0795, payoutX100: 1000, n: 4000 }, // won 318, lost 3682, void 0
    opp_promotes: { p: 0.1042, payoutX100: 882, n: 4000 }, // won 417, lost 3583, void 0
    opp_all_in_bust: { p: 0.3872, payoutX100: 237, n: 4000 }, // won 1549, lost 2451, void 0
    game_length_under: { p: 0.2505, payoutX100: 367, n: 4000 }, // won 1002, lost 2998, void 0
    game_length_over: { p: 0.5785, payoutX100: 159, n: 4000 }, // won 2314, lost 1686, void 0
  },
  'loaded_dice+all_in': {
    opp_castles_by: { p: 0.0772, payoutX100: 1000, n: 4000 }, // won 309, lost 3691, void 0
    opp_promotes: { p: 0.1098, payoutX100: 838, n: 4000 }, // won 439, lost 3561, void 0
    opp_toss_upset: { p: 0.0181, payoutX100: 1000, n: 3972 }, // won 72, lost 3900, void 28
    opp_all_in_bust: { p: 0.3655, payoutX100: 251, n: 4000 }, // won 1462, lost 2538, void 0
    game_length_under: { p: 0.3050, payoutX100: 301, n: 4000 }, // won 1220, lost 2780, void 0
    game_length_over: { p: 0.5255, payoutX100: 175, n: 4000 }, // won 2102, lost 1898, void 0
  },
  'odds_market+all_in': {
    opp_castles_by: { p: 0.0800, payoutX100: 1000, n: 4000 }, // won 320, lost 3680, void 0
    opp_promotes: { p: 0.1442, payoutX100: 637, n: 4000 }, // won 577, lost 3423, void 0
    opp_toss_upset: { p: 0.0311, payoutX100: 1000, n: 3992 }, // won 124, lost 3868, void 8
    opp_all_in_bust: { p: 0.4123, payoutX100: 223, n: 4000 }, // won 1649, lost 2351, void 0
    game_length_under: { p: 0.1840, payoutX100: 500, n: 4000 }, // won 736, lost 3264, void 0
    game_length_over: { p: 0.6440, payoutX100: 142, n: 4000 }, // won 2576, lost 1424, void 0
  },
  'loaded_dice+odds_market+all_in': {
    opp_castles_by: { p: 0.0823, payoutX100: 1000, n: 4000 }, // won 329, lost 3671, void 0
    opp_promotes: { p: 0.1437, payoutX100: 640, n: 4000 }, // won 575, lost 3425, void 0
    opp_toss_upset: { p: 0.0294, payoutX100: 1000, n: 3979 }, // won 117, lost 3862, void 21
    opp_all_in_bust: { p: 0.3875, payoutX100: 237, n: 4000 }, // won 1550, lost 2450, void 0
    game_length_under: { p: 0.2235, payoutX100: 411, n: 4000 }, // won 894, lost 3106, void 0
    game_length_over: { p: 0.5935, payoutX100: 155, n: 4000 }, // won 2374, lost 1626, void 0
  },
};
